### ISSUE TITLE
1.15.2 version does not support Fabric OBJLoader

### ISSUE THREAD

**Issue by 0x915** [modmuss50/OptiFabric#163] opened 2020-04-03 11:49 UTC
Fabric OBJLoader : https://github.com/OnyxStudios
OBJ models can be loaded when optifine is not used.
Log without any related errors or warnings.
Trying to modify the optifine settings does not resolve.

![A}L5LG$Z6TZSRT)RSE~)YRT](https://user-images.githubusercontent.com/15169084/78356532-5063d500-75e2-11ea-9e8b-1c9bd410b2f5.png)
![YN%`INYGF8 NIF)39@9N0~B](https://user-images.githubusercontent.com/15169084/78356548-535ec580-75e2-11ea-8eb0-478931634ba3.png)

![QQ截图20200403194903](https://user-images.githubusercontent.com/15169084/78357524-32976f80-75e4-11ea-94d0-b2751eb12121.png)

**Comment by 0x915** [comment] 2020-04-03 11:50
https://github.com/OnyxStudios/FOML

**Comment by modmuss50** [comment] 2020-05-05 15:09
This is prob due to optifabric not supporting the fabric rendering api.

Duplicate of #157

**Closed as completed by modmuss50** 2020-05-05 15:09 UTC
