### ISSUE TITLE
Glass pane CTM visual errors at south and east directions

### ISSUE THREAD

**Issue by RhinoKneel** [modmuss50/OptiFabric#46] opened 2019-07-22 02:05 UTC
![2019-07-21_22 59 07](https://user-images.githubusercontent.com/4513024/61601393-82c3d280-ac0b-11e9-9584-febdce75efc2.png)
![2019-07-21_22 59 36](https://user-images.githubusercontent.com/4513024/61601394-82c3d280-ac0b-11e9-9bfb-31159b9c6862.png)
![2019-07-21_23 01 26](https://user-images.githubusercontent.com/4513024/61601395-82c3d280-ac0b-11e9-850e-564681300fd9.png)

As seen in the image files, this does not occur with glass blocks, only with panes.

The ends of the glass panes appear to be using a flipped end texture instead of the one going straight through. this does not change when it connected to a solid block.

This also only occurs when looking to the south or east. North and west appear as intended.

Tested in 1.14.3 and 1.14.4 with 0.4.2 and 0.4.3

**Comment by modmuss50** [comment] 2019-07-24 16:46
I assume you tested with a basic optifine install without fabric? and it was fine?

**Comment by mrylund** [comment] 2019-07-24 18:35
> I assume you tested with a basic optifine install without fabric? and it was fine?

It's fine with a fresh install of optifine, but as soon as you use it with fabric this happens.

**Comment by Nathan22211** [comment] 2019-07-25 11:23
yeah I'm seeing the same result but i thought it was due to a resource pack

**Comment by ShuDazwei** [comment] 2019-08-10 11:43
I have the same problem. Glad I got here, I literally tried to fix my resource pack for a week or so (=

**Comment by seeruk** [comment] 2019-08-31 16:12
Does happen to me, but only when Fabric API is also being loaded. If I have Optifabric and Optifine alone (in fact, even with some other mods as long as Fabric API isn't loaded), then the glass connected textures work perfectly.

**Comment by mlakeyw03** [comment] 2019-09-20 01:35
![2019-09-19_21 08 58](https://user-images.githubusercontent.com/43811930/65291775-d5920b80-db22-11e9-9169-31e7ca68611d.png)
![2019-09-19_21 09 01](https://user-images.githubusercontent.com/43811930/65291776-d5920b80-db22-11e9-80ce-862526a6ddbb.png)
![2019-09-19_21 09 14](https://user-images.githubusercontent.com/43811930/65291777-d5920b80-db22-11e9-9b32-9e9e9d531f59.png)
![2019-09-19_21 09 16](https://user-images.githubusercontent.com/43811930/65291778-d5920b80-db22-11e9-9bde-903af9f279c4.png)
![2019-09-19_21 09 20](https://user-images.githubusercontent.com/43811930/65291780-d5920b80-db22-11e9-90fd-c8d7535adf0c.png)
![2019-09-19_21 09 29](https://user-images.githubusercontent.com/43811930/65291781-d62aa200-db22-11e9-8f00-646d68833723.png)
Ran into this bug while playing survival, textures had broken mid-session, across all tiles in the world. Used my creative world for the pictures.

Compared to the original image on the thread, the pictures are the same, but the compass where the textures appear normal is flipped for some reason. 

I have been using Optifabric for about a week, first time I have encountered this issue. My Standalone Optifine profile still works as intended, and a fresh install also works as intended. 

_If I had to guess what the issue is, it's the renderers clashing, and my speculation as to the cause of the problem is memory allocation, although further testing is need to prove this hypothesis. Only other option I can think of is the glass pane might be reading the blocks it is connected to incorectly, but this is a guess at best (I ONLY KNOW HOW GLASS PANES WORK AS A RESOURCE PACK)._

General takeaway: more visual representations, however the compass is flipped for some reason.

**Comment by seeruk** [comment] 2019-09-20 09:12
@mlakeyw03 Do you also have Fabric API loaded? Can you try it with OptiFabric, Optifine, and literally no other mods and see if it still happens for you? In my case, it only happens if I have Fabric API loaded.

**Comment by mlakeyw03** [comment] 2019-09-20 13:51
@seeruk  I tried it without fabric API and it still happens, Nothing is loaded beside Optifabric and Optifine.

**Comment by EddyNottingham** [comment] 2019-10-25 13:23
I have the issue too, using MultiMC, Optifabric 0.5.2, and OptiFine 1.14.4_HD_U_F4. If anyone is looking into this and wants me to test anything on my end just let me know, as I would love to see a fix for this :)

**Comment by greensad** [comment] 2019-11-27 17:45
Also have this issue on Vanilla Fabric build 173 on 1.14.4, Optifabric-0.7.0 and Optifine_1.14.4_HD_U_F4. Fresh install of optifine works, however fresh install of fabric+optifabric&optifine replicates the bug. Can confirm this bug was present on the last version of optifabric as well as I have a setup running that as well.

**Comment by modmuss50** [comment] 2020-02-13 18:58
Closing, the 1.14.4 version is no longer supported.

**Closed as completed by modmuss50** 2020-02-13 18:58 UTC
Labels: bug, help wanted
