### ISSUE TITLE
Crashes my game on start

### ISSUE THREAD

**Issue by SkullyFX** [modmuss50/OptiFabric#183] opened 2020-04-24 20:04 UTC
When I try to open my Minecraft game it randomly crashes, I have both Optifine and OptiFabric latest versions currently given on curseforge and optifine.net. Please help?

**Comment by Alternus** [comment] 2020-04-25 11:14
Could you please upload the crash log to https://pastebin.com/ and paste the link here

**Comment by SkullyFX** [comment] 2020-04-25 11:43
How do I get the crash report? I only got a pop up in the Minecraft
launcher that the game crashed

**Comment by Alternus** [comment] 2020-04-25 11:47
In the Launcher Settings under general tick `Open output log when games start` and `Keep the Launcher open while games are running` then copy the crash log to pastebin

**Comment by SkullyFX** [comment] 2020-04-25 12:03
Ok done, i hope i did it right :P
https://pastebin.com/zPu6E1MA

**Comment by Alternus** [comment] 2020-04-25 12:10
Ok looks good, what version of fabric are you using? and what are the specific versions of Optifine and Optifabric you have installed and do you have any other mods installed?

**Comment by SkullyFX** [comment] 2020-04-25 12:14
Fabric: 0.8.2+build.194-.1.15.2
Optifine: 1.15.2-Optifine_HD_U_G1_pre13
OptiFabric: 1.0.0-beta8

**Comment by Alternus** [comment] 2020-04-25 12:18
Alright modmuss50 will need to look further into this as i'm not sure what's causing your error

**Comment by Alternus** [comment] 2020-04-25 12:27
Double checked your crash log and it appears to be a conflict with https://github.com/THEREALWWEFAN231/wwe and similar to this issue https://github.com/THEREALWWEFAN231/wwe/issues/458 What version of that mod do you have installed?

**Comment by SkullyFX** [comment] 2020-04-25 12:33
I use the latest wwe version just downloaded it today, the optifine didn't
work yesterday aswell tho

**Comment by Alternus** [comment] 2020-04-25 12:38
Cool, so the crash is the result of that mod and not optifabric, if you could close this issue and open a new one on the [WWE github page](https://github.com/THEREALWWEFAN231/wwe/issues) detailing the crash log and the versions of your mods, hopefully the developer of that mod can fix your crash.

**Comment by SkullyFX** [comment] 2020-04-25 12:39
Ok weird, I just deleted the WWE client and it worked immediately??? Is
there a way I can keep the client without crashing?

**Comment by Alternus** [comment] 2020-04-25 12:41
Currently it would appear not, WWE appears to conflict with optifabric but based off the previous bug report posted on their github the issue is at their end. You'll need to get that mods developer to look further into this.

**Comment by modmuss50** [comment] 2020-05-05 15:09
wwe is a hacked client

**Closed as completed by modmuss50** 2020-05-05 15:09 UTC
