### ISSUE TITLE
Colors completely wrong with shaders

### ISSUE THREAD

**Issue by Decme** [modmuss50/OptiFabric#185] opened 2020-04-27 12:04 UTC
Shaders look perfect with Optifine by itself (no fabric loader)

This is what Sildur's lite shaders v1.27 look like for example with Optifabric: https://i.ibb.co/xGJLhM1/2020-04-27-12-59-18.png

1.15.2
Fabric version:
fabric-installer-0.5.2.39

Mods:

darkness-mc115-1.3.18
dynamic-fps-1.0.4
fabric-api-0.5.1+build.294-1.15
fabricmod_VoxelMap-1.9.16_for_1.15.2
LightOverlay-4.3
litematica-fabric-1.15.2-0.0.0-dev.20200212.174750
malilib-fabric-1.15.2-0.10.0-dev.20+arne.2
Mambience-1.0.0
minihud-fabric-1.15.2-0.19.0-dev.20200121.203515
optifabric-1.0.0-beta8
phosphor-fabric-mc1.15.2-0.5.2+build.6
PresenceFootsteps-r22+1.15.2
preview_OptiFine_1.15.2_HD_U_G1_pre13

**Comment by modmuss50** [comment] 2020-05-05 15:06
Duplicate of #165

**Closed as completed by modmuss50** 2020-05-05 15:06 UTC
