### ISSUE TITLE
Shaders not showing blocks and shadows properly

### ISSUE THREAD

**Issue by CrozyGamer** [modmuss50/OptiFabric#178] opened 2020-04-17 06:42 UTC
Hi, I'm having issues with shaders when I turn them on. I'm not having issues with non-fabric version of optifine. It happens to every shaderpack I use. I've even tried it without other mods but I'm still having this issue. As I said, only way for me to fix it rn is to use non-fabric version of optifine, which I don't want to because of my other mods
![2020-04-17_08 37 41](https://user-images.githubusercontent.com/56266430/79539643-091c2080-8087-11ea-9f63-eebfc687ec6d.png)
![2020-04-17_08 39 22](https://user-images.githubusercontent.com/56266430/79539671-12a58880-8087-11ea-926c-c2f9eea39bee.png)
![2020-04-17_08 39 03](https://user-images.githubusercontent.com/56266430/79539683-189b6980-8087-11ea-8327-f38989bfaea8.png)
![2020-04-17_08 38 00](https://user-images.githubusercontent.com/56266430/79539697-1cc78700-8087-11ea-9a18-abf5f6e05846.png)

**Comment by modmuss50** [comment] 2020-05-05 15:07
Duplicate of #165

**Closed as completed by modmuss50** 2020-05-05 15:07 UTC
