### ISSUE TITLE
OptiFabric keeps crashing when joining a server

### ISSUE THREAD

**Issue by LonelyAlpha** [modmuss50/OptiFabric#115] opened 2020-01-31 16:01 UTC
When i join a server it just crashes
Deleted everything part from Optifabric and optfine and still crashes.

Fabric version:
fabric-loader-0.7.6+build.180-1.14.2
fabric-api-0.4.1+build.245-1.14

Mods:
fabricmod_VoxelMap-1.9.13_for_1.14.4.jar
Autofish-Mod-Fabric-1.14.3.jar
LightOverlay-3.6.2.jar
modmenu-1.7.14.1.14.4+build.126 (1).jar
optifabric-0.7.1.jar
RoughlyEnoughItems-3.2.6+build.49.jar
ToroCrafts-Damage-Indicators-Mod-Fabric-1.14.4.jar

Optifine:
OptiFine_1.14.4_HD_U_F4.jar
Also tried OptiFine_1.14.4_HD_U_F5.jar still doesn't work

Error:
The game crashed whilst batching chunks
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

Log
https://pastebin.com/gAq4XcKw

**Comment by justastranger** [comment] 2020-02-04 01:58
I get this crash as well when trying to open a singleplayer world. Everything up until that works fine. As far as I can tell, there is an import with the wrong classpath [here](https://github.com/modmuss50/OptiFabric/blob/df03dc2c2210e7c3c0bcfe9642f3b3771a1e340f/src/main/java/me/modmuss50/optifabric/mixin/MixinChunkCacheOF.java#L4). 

Looking through the Indigo source, there does not appear to be a `net.fabricmc.fabric.impl.client.indigo.renderer.accessor.AccessChunkRendererRegion` or `net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext`, those classes instead being located at `net.fabricmc.indigo.renderer.accessor.AccessChunkRendererRegion` and `net.fabricmc.indigo.renderer.render.TerrainRenderContext`.

**Comment by brentorockz** [comment] 2020-02-04 01:58
it's happening to me as the well the same thing.

here is crash report
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/3/20 8:55 PM
Description: Batching chunks

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:776)
	at net.minecraft.class_851.method_3652(class_851.java:256)
	at net.minecraft.class_845.method_3615(class_845.java:90)
	at net.minecraft.class_845.run(class_845.java:39)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for optifabric.indigofix.mixins.json:MixinChunkCacheOF during activity: [Transform -> Method constructor(Lnet/minecraft/class_853;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> GETSTATIC -> net/fabricmc/indigo/renderer/render/TerrainRenderContext::POOLLjava/lang/ThreadLocal;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:300)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.fabricmc.indigo.renderer.render.TerrainRenderContext
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:768)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:759)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:722)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:294)
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.indigo.renderer.render.TerrainRenderContext
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:776)

-- Affected level --
Details:
	All players: 1 total; [class_746['Brentorockz'/2832977, l='MpServer', x=402.86, y=94.06, z=7767.42]]
	Chunk stats: Client Chunk Cache: 18225, 290
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,0,-16777215), Chunk: (at 0,0,1 in 0,-1048576; contains blocks 0,0,-16777216 to 15,255,-16777201), Region: (0,-32768; contains chunks 0,-1048576 to 31,-1048545, blocks 0,0,-16777216 to 511,255,-16776705)
	Level time: 168785 game time, 953058380 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.15-SNAPSHOT:4339bb7:317) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_845.run(class_845.java:45)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1135065232 bytes (1082 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth: Cloth Events 0.6.0
		cloth-config2: Cloth Config v2 1.7.3
		fabric: Fabric API 0.4.2+build.246-1.14
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.1+28f8190f42
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+28f8190f42
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+28f8190f42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.2+28f8190f42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+28f8190f42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.1+28f8190f42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.2+28f8190f42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+28f8190f42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.1+28f8190f42
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.1+28f8190f42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
		fabric-models-v0: Fabric Models (v0) 0.1.0+933c24c242
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.1+28f8190f42
		fabric-networking-v0: Fabric Networking (v0) 0.1.4+28f8190f42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.2+28f8190f42
		fabric-particles-v1: fabric-particles-v1 0.1.1+933c24c242
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.3+28f8190f42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+933c24c242
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.14+28f8190f42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.2+28f8190f42
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.3+28f8190f42
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.2+28f8190f42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.4+28f8190f42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+933c24c242
		fabricloader: Fabric Loader 0.7.6+build.181
		fiber2cloth: Fiber To Cloth 1.2.1
		litematica: Litematica 0.0.0-dev.20191222.014040
		malilib: MaLiLib 0.10.0-dev.20
		mambience: MAmbience 1.0.0+1.14
		me_zeroeightsix_fiber: fiber 0.6.0-7
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.8
		optifabric: Optifabric 0.7.0
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_slf4j_slf4j-simple: slf4j-simple 1.7.29
		org_zeroturnaround_zt-zip: zt-zip 1.13
		roughlyenoughitems: Roughly Enough Items 3.2.8+build.51
		voxelmap: VoxelMap 1.9.13
	Launched Version: fabric-loader-0.7.6+build.181-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/MassiveCraft-V32.zip
	Current Language: English (US)
	CPU: 4x AMD FX(tm)-4350 Quad-Core Processor 
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 30
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13586 Compatibility Profile Context 19.12.2 26.20.15002.61
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by MRcoin2** [comment] 2020-02-08 10:43
Same thing for me. :c 

---- Minecraft Crash Report ----
// My bad.

Time: 08.02.20 11:34
Description: Batching chunks

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:776)
	at net.minecraft.class_851.method_3652(class_851.java:256)
	at net.minecraft.class_845.method_3615(class_845.java:90)
	at net.minecraft.class_845.run(class_845.java:39)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for optifabric.indigofix.mixins.json:MixinChunkCacheOF during activity: [Transform -> Method constructor(Lnet/minecraft/class_853;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> GETSTATIC -> net/fabricmc/fabric/impl/client/indigo/renderer/render/TerrainRenderContext::POOLLjava/lang/ThreadLocal;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:300)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:768)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:759)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:722)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:294)
	... 17 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:776)

-- Affected level --
Details:
	All players: 1 total; [class_746['MRcoin'/48, l='MpServer', x=101.62, y=12.00, z=187.63]]
	Chunk stats: Client Chunk Cache: 3025, 2401
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (113,4,152), Chunk: (at 1,0,8 in 7,9; contains blocks 112,0,144 to 127,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 54913 game time, 54913 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_845.run(class_845.java:45)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 943576616 bytes (899 MB) / 1728053248 bytes (1648 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		fabric: Fabric API 0.3.2+build.218-1.14
		fabric-api-base: fabric-api-base 0.1.0+b494ebeb42
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.13+68fade5542
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.3+b02deb0042
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.7.8+build.184
		litematica: Litematica 0.0.0-dev.20190720.191654
		malilib: MaLiLib 0.10.0-dev.20
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.8
		optifabric: Optifabric 0.7.1
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_slf4j_slf4j-simple: slf4j-simple 1.7.29
		org_zeroturnaround_zt-zip: zt-zip 1.13
	Launched Version: fabric-loader-0.7.8+build.184-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, programer_art
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 26
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.66
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by modmuss50** [comment] 2020-02-13 18:57
Closing, the 1.14.4 version is no longer supported.

**Closed as completed by modmuss50** 2020-02-13 18:57 UTC
