### ISSUE TITLE
Causing open gl error 1281(invalid value)

### ISSUE THREAD

**Issue by rsmyst** [modmuss50/OptiFabric#25] opened 2019-06-14 07:23 UTC
For some reason using optifabric causes me to have open gl qrror 1281 which also causes the blocks to not render! This is really annoying as none of the blocks appear and only water is visible.

**Comment by modmuss50** [comment] 2019-06-28 11:49
duplicate of #26

**Closed as completed by modmuss50** 2019-06-28 11:49 UTC
