### ISSUE TITLE
Batching chunks

### ISSUE THREAD

**Issue by Kasinel** [modmuss50/OptiFabric#37] opened 2019-07-07 20:12 UTC
https://gist.github.com/Kasinel/b52d8c9b2a7b4cb80ad3b279045e11b2

**Comment by modmuss50** [comment] 2019-07-09 13:11
Does this always happen? Did you change any settings?

Can you try updating OptiFabric?

**Comment by Mintelgen** [comment] 2019-07-10 09:00
Not sure if it's the same symptom, but I also consistently crash with the "Batching Chunks" description.

This seems to only happen when I have smooth lighting enabled and/or any percent of its level while near complicated redstone contraptions. OptiFine or Fabric alone doesn't cause the crash; it only happens when OptiFabric is enabled.

I can reproduce it every time using the Gnembon Sorter in the world below. My game crashes instantly the moment it starts sorting. This isn't the only case either; some machines likes Ilmango's industrial 0-tick sugar cane/bamboo farms also causes crashes when they turn on.

Crash log: [crash-2019-07-10_02.38.14-client.txt](https://github.com/modmuss50/OptiFabric/files/3376545/crash-2019-07-10_02.38.14-client.txt)
World to test (needs unzipping): [lagfree_sorter.zip](https://github.com/modmuss50/OptiFabric/files/3376558/lagfree_sorter.zip)

**Comment by modmuss50** [comment] 2019-07-10 15:51
Im struggling to repoduce this, using the world you linked seems to work fine.

I tried using settings provided by a user on the discord that were kown to cause a crash but that didnt provide me with anything.

The cause of the crash seems to be coming from `fabric-rendering-data-attachment` with [this mixin](https://github.com/FabricMC/fabric/blob/master/fabric-rendering-data-attachment-v1/src/main/java/net/fabricmc/fabric/mixin/rendering/data/client/MixinChunkRendererRegion.java#L39)

My best guess is with the `chunkB.getBlockEntities().entrySet()` line. Im not sure on the steps I would need to take to atempt to fix this?

**Comment by Mintelgen** [comment] 2019-07-10 16:49
Sorry, I should've clarified earlier that I had both the API and Loader for that crash log (I presumed it was needed for OptiFabric to work).

I just did some more testing with and without the API using the same world, and it seems that whenever it's enabled, the crash happens; if it's not enabled, my CPU just maxes out at 100% usage, though I assume that's more of problem with my hardware's specs.

I recall needing to use a workaround in the indigo-renderer.properties file for past versions of OptiFabric & Fabric API, so maybe the culprit is actually something from Fabric API instead?

**Comment by modmuss50** [comment] 2019-07-10 17:00
That work around isnt needed any more, do you still have the config values changed? If so delete that config file and let it regenerate? does that fix it?

Fabric API and Loader are both required and both should be on the newest version. The API is optinal but is needed for most mods so it is generally recomened to have it installed.

**Comment by Mintelgen** [comment] 2019-07-10 17:08
The crash still occurs regardless of whether the config file is old or fresh.

**Comment by modmuss50** [comment] 2019-07-10 23:59
What Graphics card are you guys using?

**Comment by Kasinel** [comment] 2019-07-11 00:02
my is gtx 1050 ti, this bug occurs when I use /ticks warp from carpet mod near redstone

**Comment by Mintelgen** [comment] 2019-07-11 05:06
My GPU is a GTX 970M running on driver version 430.86 (it's about as powerful as the 1050 Ti).

**Comment by modmuss50** [comment] 2019-07-11 13:57
Humm, ok thanks, the other person I was speaking to was using AMD and his friend didnt have the same issue (same settings and what not) on an nvidia card.

Is this happening in single player for you guys?

@Kasinel can you link me to that mod as I found one version of it but it doesnt seem to have that command.

**Comment by modmuss50** [comment] 2019-07-11 14:07
Good news, I messed around with the carpet mod and was able to repoduce it! Now to try and fix it.

**Comment by Kasinel** [comment] 2019-07-11 14:26
My mods:
QuickCarpet114: https://github.com/DeadlyMC/QuickCarpet114#quickcarpet114
OptiFine_1.14.3_HD_U_F1
optifabric-0.3.2
fabric-api-0.3.0+build.188

Test World: https://www.mediafire.com/file/m6f8p6066mh41p4/precise+furnace+array+ilmango.zip
Turn on smelter and use command /tick warp 72000 

Now i update my all mods and start testing this

**Comment by Kasinel** [comment] 2019-07-11 14:34
Now update optifabric and fabric-api to latest, and I have the same issue when i use /tick warp 72000 command from quickcarpet mod

**Comment by Kasinel** [comment] 2019-07-11 17:42
I build ilmango Bamboo Farm on survival and when i start the farm i have this same bug. Crash: batching chunks

ilmango Tutorial: https://youtu.be/hMtFHU6f9c0
no mods on server, just optifine and optifabric in my client

**Comment by etz** [comment] 2019-07-17 06:13
I'm receiving the same issues Kasinel has. I downloaded Optifine 1.14.3 + Optifabric for the first time after building ilmango's 0-tick bamboo farm and am now unable to load into the game without crashing.

My log: https://pastebin.com/raw/TmnLAgH4

**Comment by ahkui** [comment] 2019-07-17 11:09
same issue 
[crash-2019-07-17_19.01.34-client.txt](https://github.com/modmuss50/OptiFabric/files/3401555/crash-2019-07-17_19.01.34-client.txt)

**Comment by ghost** [comment] 2019-07-19 06:16
Here to report that the same issue occurs on my private server when I /home from any location if my house is previously unloaded. Logging in at my house, the crash doesn't occur. This also didn't occur until _after_ I had built a large potato farm, as well as a hopper junction (fairly large, as well).
https://pastebin.com/raw/VGVtn71A

**Comment by modmuss50** [comment] 2019-07-19 10:32
Thanks for reporting the issue, however I have no idea how to fix it, so if someone knows please let me know. Even if its just an idea, even better make a PR to optifabric.

(There is no benefit to posting more crash logs on this issue from here onwards, thanks)

**Comment by grondag** [comment] 2019-07-30 04:15
Best bet is the problem is happening here:  https://github.com/FabricMC/fabric/blob/master/fabric-rendering-data-attachment-v1/src/main/java/net/fabricmc/fabric/mixin/rendering/data/client/MixinChunkRendererRegion.java

That's the code Fabric uses to cache Block Entity data in a thread-safe way for access during chunk rebuilds.

Question is, how is the CME happening. Could be that OF is somehow concurrently modifying the BlockEntity map that is  accessed via `chunkB.getBlockEntities().entrySet())`.

One fix might be to capture that map to an array or immutable collection before iteration.

**Comment by maruohon** [comment] 2019-07-30 08:55
```
    at net.minecraft.class_853.handler$init$zbb000(class_853.java:1045)
    at net.minecraft.class_853.<init>(class_853.java:108)
    at net.minecraft.class_853.generateCache(class_853.java:90)
    at net.minecraft.class_851.createRegionRenderCache(class_851.java:785)
    at net.minecraft.class_851.makeChunkCacheOF(class_851.java:774)
    at net.minecraft.class_851.method_3652(class_851.java:256)
```
`method_3652 => rebuildChunk` 

To me it looks like OptiFine is then trying to build the chunk cache in the `rebuildChunk` method, which can run on the render threads instead of caching the state on the main thread?

In 1.14 vanilla creates the cache in the `ChunkRenderer#startRebuild()` method, which is called from `ChunkBatcher#rebuild()` and `ChunkBatcher#rebuildSync()` methods, which are called from the `WorldRenderer#setupTerrain()` and `WorldRenderer#updateChunks()` methods, which are only called from the main client thread.

Thus it looks like Optifine is caching stuff from off the main thread, and thus setups where BlockEntities are created and destroyed regularly would quickly run into the CME while trying to cache the BlockEntities from a render thread.

**Comment by grondag** [comment] 2019-07-31 02:14
Yeah, if OF is building the cache from the render threads that would do it, and it would be intermittent too.  It's also cheating. ;-). There's reasons vanilla does the cache on the client thread.

Asie's code for building the cache uses the chunk entity map as an optimization, but could instead simply iterate the captured block states to find blocks that have a BE and then request them via `Chunk.getBlockEntity(blockPos)` (checking for and handling nulls, of course).  That may not be as fast but should not CME. Ideally use a ThreadLocal mutable block pos to avoid needless allocation.

**Comment by Darciah** [comment] 2019-08-17 19:20
I'm also getting this crash/error. I've noticed that the crash tends to happen with your client is trying to process 300+ chunk updates (usually with intense redstone going on around the user). Idk if that helps at all, but wish you well in finding a solution.

**Comment by TharenaMelishka** [comment] 2019-08-27 12:49
I get this crash regularly if I am running the ilmango bamboo farm and then *look away* from it, so it's rendering / doing it's thing in the background.  It doesn't happen every time, so there's something else at play, but I do NOT crash if the redstone isn't running, and semi-frequently crash if I turn it on and look away in less than 2 minutes after starting it up.  I also was getting this crash when running a long series of note blocks and the redstone was pulsing at a point where I couldn't see it visually on the screen.  It so far hasn't crashed if I'm staring at the entire contraption, just if there's part of it I can't see and it updates.  

Hope that helps!

**Comment by kosma** [comment] 2019-09-03 13:37
How long do those operations take? Perhaps mutexing the relevant data (and patching Optifine to use that mutex) would help? That's just a though; I don't know enough Minecraft architecture to understand consequences of that.

**Comment by modmuss50** [comment] 2019-09-13 15:53
To make things even more intresting this has been reproduced without optifine.

[crash-2019-09-12_22.24.59-client.txt](https://github.com/modmuss50/OptiFabric/files/3610764/crash-2019-09-12_22.24.59-client.txt)

**Comment by grondag** [comment] 2019-09-13 16:25
Any mod that updates the per-chunk block entity map outside the main client thread could cause this, as could any attempt to bake chunks outside the main client thread. 

What needs to happen is for Fabric API to use a thread-safe iteration/lookup method vs iterating the map entry set directly.  I can do that PR, though it may be a little while until I get to it.

**Comment by grondag** [comment] 2019-09-14 02:50
There is now a Fabric [test build](https://github.com/grondag/fabric/releases/download/Fix366Test1/fabric-rendering-data-attachment-v1-0.1.1+1436934f42.jar) that _may_ fix the problem.  Please try it out and report back.

**Comment by kosma** [comment] 2019-09-14 19:58
On my initial testing I no longer get crashes while running 0-tick farms. Will run this for a while and seen if there are any other issues.

**Comment by TharenaMelishka** [comment] 2019-09-27 15:06
> 
> 
> There is now a Fabric [test build](https://github.com/grondag/fabric/releases/download/Fix366Test1/fabric-rendering-data-attachment-v1-0.1.1+1436934f42.jar) that _may_ fix the problem. Please try it out and report back.

Edit:  I THINK I have it working correctly.  I also updated to current Fabric build in the process, and used MultiMC to run the attachment as additional to the current build.  The zero tick farm that was crashing my client within 2 seconds of starting it now no longer crashes it.  I'd call that a good sign.  Will be building more in next week, will report back after testing.


Initial Bonehead Statement:  :)
I'm not sure I understand how to use this jar... Does the server need to use it too, or do I just add it... to the launcher as a new version... which I can't seem to figure out how to do properly.  I'd love to test this, I just don't understand how to implement it. 

Thanks!

**Comment by modmuss50** [comment] 2019-09-29 21:17
This should now be fixed with the updated fabric API version, thanks for the help and patience everyone.

**Closed as completed by modmuss50** 2019-09-29 21:17 UTC
Labels: bug, help wanted
