### ISSUE TITLE
Textures are not shown properly

### ISSUE THREAD

**Issue by ghost** [modmuss50/OptiFabric#166] opened 2020-04-04 18:23 UTC
Purple Grass and leaves.
https://user-images.githubusercontent.com/60066759/78458455-65f00200-76a9-11ea-99ee-f1130548a8c2.png
Version - 1.15.2
Shaders - Sildur's Vibrant shaders v1.27 Medium
Tested shaders (Similar outcomes) - Kuda Legacy, Sildur's Vibrant shaders v1.27 Lite and Sildur's Vibrant shaders v1.27 High.
I've tested both beta7 and beta8 optifabric

Please help.

**Comment by ghost** [comment] 2020-04-04 18:28
Update: If trees are set to Fast in the Detail settings they return to their normal texture.

**Comment by modmuss50** [comment] 2020-04-07 13:33
does this happen without optifabric? (if you install optfine on its own)

**Comment by ghost** [comment] 2020-04-07 22:09
I haven't yet, I'll do so in the morning

**Comment by howardt12345** [comment] 2020-04-18 22:44
> does this happen without optifabric? (if you install optfine on its own)

I have this issue as well, and no it doesn't without optifabric.

**Comment by modmuss50** [comment] 2020-05-05 15:07
Duplicate of #165

**Closed as completed by modmuss50** 2020-05-05 15:07 UTC
Labels: more info needed
