### ISSUE TITLE
Crash on version 1.15.2 with Opti G1 pre2

### ISSUE THREAD

**Issue by SnrSterling** [modmuss50/OptiFabric#132] opened 2020-02-17 12:45 UTC
Pastebin crashlog: https://paste.ee/p/rC6ws
i dont know how fix it. Help please.

**Comment by justastranger** [comment] 2020-02-17 13:10
My game is also crashing, but with a different crash.

https://paste.ee/p/wEoYQ

**Comment by modmuss50** [comment] 2020-02-17 13:46
Seems to be due to Tweakeroo, try updating or removing it. Duplicate of #126

**Closed as completed by modmuss50** 2020-02-17 13:46 UTC

**Comment by SnrSterling** [comment] 2020-02-17 14:09
Without mod Tweakeroo, too, the same crash. And without All mods, same only OptiFabric + FabricAPI + Optifine = crash

**Comment by SnrSterling** [comment] 2020-02-17 14:14
> Without mod Tweakeroo, too, the same crash. And without All mods, same only OptiFabric + FabricAPI + Optifine = crash

Okay, the problem was in conflicts mods: REI and Tweakeroo
