### ISSUE TITLE
CTM has non-connected textures on glass. 1.15.2 OF Preview G1_Pre2

### ISSUE THREAD

**Issue by LyCH-OS** [modmuss50/OptiFabric#130] opened 2020-02-15 17:50 UTC
Like it says in the title. Heres a gif of the issue.
I've been told it's an OptiFabric issue and not an Optifine one. Hopefully it's not hard to fix.

https://puu.sh/FaWth/6183cc2be2.gif

**Comment by DonSerrot** [comment] 2020-02-16 01:56
I've had this happening to me with glass panes since at least 1.14.4. I've not noticed anything like this with regular glass.

**Comment by modmuss50** [comment] 2020-02-16 13:16
I have no idea why this happens

**Comment by ilepow34** [comment] 2020-02-17 23:37
It looks like the textures on the "back" side of glass panes (north side when the panes are oriented east-west, east side when they're oriented north-south) are mirrored from their normal texture, which is most noticeable on the end pieces. This only occurs when using OptiFine via OptiFabric.
![2020-02-17_17 25 07](https://user-images.githubusercontent.com/8581976/74692136-7d336880-51ab-11ea-8e43-016548dad46f.png)
![2020-02-17_17 25 11](https://user-images.githubusercontent.com/8581976/74692137-7e649580-51ab-11ea-9e23-36b30628fc6a.png)
![2020-02-17_17 25 20](https://user-images.githubusercontent.com/8581976/74692138-7efd2c00-51ab-11ea-9830-2151432df606.png)
![2020-02-17_17 25 22](https://user-images.githubusercontent.com/8581976/74692140-7f95c280-51ab-11ea-9a0f-620be11394a2.png)
![2020-02-17_17 25 30](https://user-images.githubusercontent.com/8581976/74692141-80c6ef80-51ab-11ea-957f-5fb03fedb6c7.png)
![2020-02-17_17 25 31](https://user-images.githubusercontent.com/8581976/74692142-815f8600-51ab-11ea-9553-22213b01c1bf.png)
![2020-02-17_17 25 38](https://user-images.githubusercontent.com/8581976/74692145-81f81c80-51ab-11ea-8985-937215d74100.png)
![2020-02-17_17 25 39](https://user-images.githubusercontent.com/8581976/74692147-8290b300-51ab-11ea-8b39-c9376dad7d85.png)

This does not occur when using only OptiFine.
![2020-02-17_17 27 55](https://user-images.githubusercontent.com/8581976/74692148-83294980-51ab-11ea-98d1-2ebe6c925881.png)
![2020-02-17_17 27 59](https://user-images.githubusercontent.com/8581976/74692151-83294980-51ab-11ea-95aa-1d099218280c.png)

It only seems to affect the glass panes, not the other blocks that use connected textures like glass blocks, sandstone, and bookshelves.

**Comment by ilepow34** [comment] 2020-02-18 00:11
For clarity, in the first set of screenshots, I'm running the following:

- Minecraft 1.15.2
- Fabric loader 0.7.8 build 184
- OptiFabric 1.0.0 beta 4
- Optifine 1.15.2 G1 pre3

**Comment by ilepow34** [comment] 2020-02-18 06:54
After playing around a bit, I've found that this bug was caused by a change in fabric api between builds 197 and 198. This means it would have first been noticed in OptiFabric 0.4.3, the first version to support Minecraft 1.14.4, since its minimum fabric api version was bumped from 0.3.0 build 191 to 0.3.0 build 200. I'll see if I can't track down the associated commit in https://github.com/FabricMC/fabric/

**Comment by ilepow34** [comment] 2020-02-18 06:59
In both sets of screenshots, I'm running Minecraft 1.14.3 with Fabric loader 0.4.8 build 155, OptiFine 1.14.3 F2, and Optifabric 0.4.2. 

Fabric API 0.3.0 build 197
![2020-02-18_00 54 58](https://user-images.githubusercontent.com/8581976/74711400-880cee00-51e9-11ea-8a02-0e98c5f0cf02.png)
![2020-02-18_00 55 08](https://user-images.githubusercontent.com/8581976/74711404-89d6b180-51e9-11ea-9eeb-f6e6669e8812.png)

Fabric API 0.3.0 build 198
![2020-02-18_00 56 05](https://user-images.githubusercontent.com/8581976/74711407-8a6f4800-51e9-11ea-8664-4b2ae1c5f8f4.png)
![2020-02-18_00 56 13](https://user-images.githubusercontent.com/8581976/74711411-8b07de80-51e9-11ea-819c-80675e506916.png)

**Comment by modmuss50** [comment] 2020-02-18 10:58
I think I have an idea why this isnt working correctally. I dont think Fabric API is adding optifine as a resource pack.

**Comment by ilepow34** [comment] 2020-02-18 18:33
Based on the timestamps on GitHub and CurseForge I think this is the commit that caused it: https://github.com/FabricMC/fabric/commit/7495ea28d67dc49fbdc90015689fff8f4d708781

Should I open an issue there too?

**Comment by modmuss50** [comment] 2020-02-29 19:30
I think I need to add optifine as a resource pack ontop of being a mod.

**Comment by grn-kunnnn** [comment] 2020-03-07 15:59
I didn’t understand anything, but when it will fixed?
Sorry for the dumb question.

**Comment by modmuss50** [comment] 2020-03-27 13:15
I think ive made some progress fixing this.

![](https://ss.modmuss50.me/java_2020-03-27_13-14-09.png)

It did require adding optifine as a fake resource pack, I dont think this will cause any issues:

![](https://ss.modmuss50.me/java_2020-03-27_13-15-08.png)

This fix will be included in the next beta version.

**Closed as completed by modmuss50** 2020-03-27 13:15 UTC
Labels: bug, help wanted

**Comment by Mixtongent73** [comment] 2020-07-11 00:13
The pack used to fix this issue does not allow for users to use the Programmer Art pack.
