### ISSUE TITLE
Shaders don't work properly

### ISSUE THREAD

**Issue by Poizenes** [modmuss50/OptiFabric#14] opened 2019-05-31 10:47 UTC
Hey there,

I used a shader with optifine 1.14.2 and it worked very well.
But with the fabric launcher and optifabric, shaders are a absolute mess. I tested it with multiple shaders including Sildurs Vibrant Shaders, BSL+ and the internal shader. 
I attached a screenshot. All shaders I tested, looked like this.
![2019-05-31_12 40 27](https://user-images.githubusercontent.com/36055495/58701011-0991c700-83a2-11e9-8140-caac66790356.png)

I hope you can fix this problem. I really appreciate your mod.

**Comment by calloatti** [comment] 2019-05-31 10:51
> may have issues with shaders, a fix is being worked on.

From https://minecraft.curseforge.com/projects/optifabric

Known issue, may be fixed at some point probably.

**Comment by Poizenes** [comment] 2019-05-31 10:57
Okay, thank you for the quick answer

**Comment by modmuss50** [comment] 2019-05-31 11:01
duplicate of #10

**Closed as completed by modmuss50** 2019-05-31 11:01 UTC
