### ISSUE TITLE
Shaders not properly working with 1.15.2

### ISSUE THREAD

**Issue by ghost** [modmuss50/OptiFabric#182] opened 2020-04-24 15:28 UTC
With the newest OptiFabric version and the newest pre-release of OptiFine for 1.15.2 shaders are not working properly.
Metal objects (hoppers, iron doors, etc.) and chests for example have texture glitches an "shimmer".
Running the same shaders and OF version without Fabric it's fine.

**Comment by modmuss50** [comment] 2020-05-05 15:06
Duplicate of #165

**Closed as completed by modmuss50** 2020-05-05 15:06 UTC
