### ISSUE TITLE
Crash around pistons activating (1.14.4)

### ISSUE THREAD

**Issue by vivalabrock** [modmuss50/OptiFabric#61] opened 2019-08-18 04:33 UTC
Any time I am around updating pistons (sometimes just randomly in general) or say, using an auto tree farm, my game will just crash out instantly.. or Ill get some weird, insane visual glitch that locks up my game when I F3+T to reload my textures. I am the only one on the server I am on who has these issues it seems.

![image](https://user-images.githubusercontent.com/26517658/63220137-ce46ad80-c1c4-11e9-8164-9a1007de7782.png)

These are the mods I am using, I am on the vanilla launcher. I am using the latest build (159) and if it matters, I use Sildurs Enhanced Default v1.081 shaders.

This is on a server with Paper and a few plugins.

https://pastebin.com/a5DD58Ew
this was my latest crash report..

**Comment by vivalabrock** [comment] 2019-08-18 04:36
https://pastebin.com/a5DD58Ew

this was my latest crash report..

**Comment by modmuss50** [comment] 2019-08-18 15:34
Duplicate of https://github.com/modmuss50/OptiFabric/issues/37

**Closed as completed by modmuss50** 2019-08-18 15:34 UTC
