### ISSUE TITLE
it doesn't work in 1.14.2with API175 and optifine 

### ISSUE THREAD

**Issue by nikissXI** [modmuss50/OptiFabric#13] opened 2019-05-31 08:37 UTC
![image](https://user-images.githubusercontent.com/31379266/58692966-52f20e80-83c2-11e9-8c77-a191d5b64c7d.png)

**Comment by arturek1666** [comment] 2019-05-31 08:42
This is becouse if I am correct you use shaders, The author is aware of this ussue. For now just disable shaders :)

**Comment by nikissXI** [comment] 2019-05-31 09:16
> This is becouse if I am correct you use shaders, The author is aware of this ussue. For now just disable shaders :)

OK，thanks

**Comment by calloatti** [comment] 2019-05-31 10:52
![image](https://user-images.githubusercontent.com/12817862/58701352-0df5ba00-8379-11e9-941b-1e0660e1f4c6.png)

**Comment by modmuss50** [comment] 2019-05-31 11:01
duplicate of #10

**Closed as completed by modmuss50** 2019-05-31 11:01 UTC
