### ISSUE TITLE
crashes with OptiFine 1.14 HD U F1 pre4 fabric 1.14-21

### ISSUE THREAD

**Issue by SDUBZ** [modmuss50/OptiFabric#5] opened 2019-05-24 11:11 UTC
[crash-2019-05-24_20.52.49-client.txt](https://github.com/modmuss50/OptiFabric/files/3216562/crash-2019-05-24_20.52.49-client.txt)

**Comment by modmuss50** [comment] 2019-05-24 11:13
This is due to Arcane Magic's mixins. And a duplicate of #3.

Arcane Magic should move over to the fabric rendering api.

**Closed as completed by modmuss50** 2019-05-24 11:13 UTC

**Comment by SDUBZ** [comment] 2019-05-24 11:18
ok thanks :)
