### ISSUE TITLE
Game crashes when taking a screenshot with ScreenshotToClipboard Mod

### ISSUE THREAD

**Issue by elhertz** [modmuss50/OptiFabric#131] opened 2020-02-17 01:15 UTC
[ScreenshotToClipboard Mod](https://www.curseforge.com/minecraft/mc-mods/screenshot-to-clipboard-fabric)
Log: https://hastebin.com/ekowoqiqat.md
(ScreenshotToClipboard works fine without optifabric-optifine)

**Comment by amnotbananaama** [comment] 2020-02-18 07:11
This is a duplicate of my previously closed issue, I wasn't sure if I should open a new issue or wait for mine to be re-opened. https://github.com/modmuss50/OptiFabric/issues/112

**Comment by modmuss50** [comment] 2020-03-27 13:46
I fixed screenshots, I assume it was the same bug

**Closed as completed by modmuss50** 2020-03-27 13:46 UTC
