### ISSUE TITLE
[1.15.2] Crashes with newest Optifine previews (pre7-pre8)

### ISSUE THREAD

**Issue by justastranger** [modmuss50/OptiFabric#142] opened 2020-02-23 03:31 UTC
Tested with preview 7 and 8. Last known good version for me was preview 3, but I don't have the previews in-between to test.

https://paste.ee/p/TUfdj

**Comment by yuiidev** [comment] 2020-02-23 04:36
Same here. Pre 7 & 8 crash when entering a world.
Never had an earlier build so I can't comment on those.

**Comment by Mewtwoy** [comment] 2020-02-23 20:29
This web page at paste.ee has been reported as a malware page.

**Comment by Mewtwoy** [comment] 2020-02-23 20:34
Nice scummy practice by the developer of optifine, i tried to download preview 3, which i did a few days ago, guess what? file not found.
Tried with previews from 4 to 9, only 9 works, good work deleting the old versions and forcing us to use new broken ones which don't even work with forge, and now not even fabric, HOW ARE WE SUPPOSED TO LOAD IT THEN?!?

**Comment by modmuss50** [comment] 2020-02-24 10:01
Ill take a look as soon as I have a chance.

**Comment by Southpaw1496** [comment] 2020-02-24 10:14
Preview 10 is working for me with Beta 4.

**Comment by modmuss50** [comment] 2020-02-24 13:42
Seems to be working for me, that crash you posted could be a mod compat issue with Terrestria? Can you try without mods?

**Comment by TheXug** [comment] 2020-02-24 19:59
I just tried it without mods and it worked.

**Comment by modmuss50** [comment] 2020-02-24 23:04
Closing as a duplicate of #139

**Closed as completed by modmuss50** 2020-02-24 23:04 UTC
Labels: bug

**Comment by SeasonalFerret** [comment] 2020-03-16 19:41
Is it possible to update the title of this issue? Got a bit confused without reading comments, this is one of the first results when googling if fabric 1.15.2 is compatible with optifine
