### ISSUE TITLE
Displays error message with "Immersive Portals" Mod

### ISSUE THREAD

**Issue by Crazymotoman03** [modmuss50/OptiFabric#71] opened 2019-09-25 02:21 UTC
When in a world, there is a message in the chat saying that there is an OpenGL error. I'm unsure of what this means since I'm very new to using mods, but I have figured out that it is the 'Immersive portals" fabric mod that is causing the given issue. The message only shows up if shaders are active. This issue does not affect gameplay, as everything appears to run fine, but I find the message rather annoying, and I can not turn of chat because I use many commands.

![2019-09-24_20 22 53](https://user-images.githubusercontent.com/55772187/65563985-0aca9f00-df11-11e9-8fce-b49845a6552d.png)

**Comment by Nex-Stargaze** [comment] 2019-09-25 15:03
Those openGL errors come with optifine itself, if your game still runs fine, you can either ignore them, or turn them off in the options via Settings >Video Settings > Other > Show GL Errors: Off

**Comment by qouteall** [comment] 2019-12-01 09:44
This error may be caused by Immersive Portals. You can ignore it if nothing unusual shows.

**Comment by modmuss50** [comment] 2020-02-13 18:58
Closing, the 1.14.4 version is no longer supported.

**Closed as completed by modmuss50** 2020-02-13 18:58 UTC
